repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
        exclude: "{{cookiecutter.repo_name}}/(bitbucket-pipelines.yml|.github/workflows/python-build.yml)"
    -   id: check-shebang-scripts-are-executable
    -   id: end-of-file-fixer
        exclude: ^\.(idea|vscode)/.*
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
    -   id: yesqa
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: tests/
        additional_dependencies: [flake8-docstrings]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    -   id: autoflake
        args:
        -   "--in-place"
        -   "--expand-star-imports"
        -   "--remove-all-unused-imports"
        -   "--ignore-init-module-imports"
